UICR-132: Results List | Apply Results list column chooser
folio-org/ui-courses pull request #155
Opened 2021-07-06 11:24 UTC by mariiaschv

## Purpose
Implemented `<ColumnManager>` for managing visible columns in the results list.

Issue: [UICR-132](https://issues.folio.org/browse/UICR-132)

## Screenshots
![image](https://user-images.githubusercontent.com/84023879/124592060-b5e9e580-de65-11eb-85fe-1ba948218978.png)

2021-07-06 11:32 UTC, MikeTaylor approved these changes
Looks good!

2021-07-07 14:45 UTC, BogdanDenis requested changes
Just a small code style comment to fix and all will be great!

2021-07-07 14:45 UTC, BogdanDenis commented on src/components/Courses.js
> +        <MenuSection label={intl.formatMessage({ id: 'ui-courses.actions' })} id="actions-menu-section">
Please move each prop to a new line

2021-07-07 16:04 UTC, BogdanDenis approved these changes

2021-07-07 16:05 UTC, merged